### ISSUE TITLE
Allow fiber extraction

### ISSUE THREAD

**Issue by caethan** [caethan/urw-sufficiency#2]
Should be able to extract fibers from flax, hemp, and nettle plants through retting.  Need to decide how to handle it --- whole plants (blocks threshing out seeds, leaves, and flowers for food) or some subpart (probably leaves).

Once retted, there will be several stages to get to yarn, then weaving/knitting to make cloth and clothing.

**Comment by fabioticconi** [comment]
I think the whole plant would be more interesting - the farmer will need to think about how much to plant for both clothing and food.

PS: "Rains cloth" has a great weaving component, with a nice long process from the whole plant to the cloth. The hemp recipes would just need to be duplicated for flax, only for the initial stages since both will fall into the "linen cloth" category.

**Comment by caethan** [comment]
Yeah, I'm kind of leaning towards whole plant myself.  I read some real-world stuff on fibre retting and the plants were usually gathered before ripening/seed harvesting, meaning that it really was exclusive food use/fiber use.  I've seen Rain's cloth mod --- it's awesome, and planning to adopt a fair bit of it once I get the chance.
